from __future__ import annotations

SOURCE_DT = 0.05
CONTROL_DT = 0.005
DEFAULT_SOURCE_HZ = 20.0
DEFAULT_CONTROL_HZ = 200.0
DEFAULT_SUBSTEPS = 10
NUM_PIANO_KEYS = 88
DEFAULT_OUTPUT_ROOT = "/WAVE/datasets/ccoelho_lab-jlanders/Ballade"
REDUCED_ACTION_DIM = 39
RIGHT_HAND_SLICE_39D = slice(0, 19)
LEFT_HAND_SLICE_39D = slice(19, 38)
SUSTAIN_INDEX_39D = 38
